apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-aves
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-aves
    app.kubernetes.io/part-of: ci10t-777-0038-app
  name: devfile-sample-aves
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-aves
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-aves
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0038-tenant/ci10t-777-0038-app/devfile-sample-aves@sha256:7469fbcd2f23abf7aad83b53ba95a10fcb11d59e4d3133496eaa553240412807
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
